# Site Settings
locale: "en-US"
title: "Applied Galactic Dynamics"
title_separator: "-"
name: "CCA Dynamics Group"
remote_theme: amitmerchant1990/reverie
url: http://galacticdynamics.nyc

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/orbit.png

# Google Analytics web tracking code
google_analytics: UA-153692380-1

# Page config
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM  # GitHub flavored Markdown
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


include: ['_pages']

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from


# Includes an icon in the footer for each username you enter
footer-links:
  email:
  github: CCADynamicsGroup/SummerSchoolWebsite


# Exclude these files from your production site
exclude:
  - LICENSE
  - README.md
  - CNAME